//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMaster
    {
        public GroupMaster()
        {
            this.GroupMaster1 = new HashSet<GroupMaster>();
        }
    
        public short ID { get; set; }
        public string GroupName { get; set; }
        public Nullable<short> ParentGroupID { get; set; }
        public string Description { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<GroupMaster> GroupMaster1 { get; set; }
        public virtual GroupMaster GroupMaster2 { get; set; }
    }
}
